AWSTemplateFormatVersion: '2010-09-09'
Description: Application Load Balancer and Target Groups

Resources:
  GalleryALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP
      VpcId: !ImportValue GalleryVPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  GalleryALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: GalleryALB
      Scheme: internet-facing
      Subnets:
        - !ImportValue GalleryPublicSubnet1
        - !ImportValue GalleryPublicSubnet2
      SecurityGroups:
        - !Ref GalleryALBSecurityGroup

  GalleryALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref GalleryFrontendTargetGroup
      LoadBalancerArn: !Ref GalleryALB
      Port: 80
      Protocol: HTTP

  GalleryFrontendTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: gallery-frontend-tg
      Port: 80
      Protocol: HTTP
      VpcId: !ImportValue GalleryVPCId
      TargetType: ip
      HealthCheckPath: /

  GalleryBackendTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: gallery-backend-tg
      Port: 8080
      Protocol: HTTP
      VpcId: !ImportValue GalleryVPCId
      TargetType: ip
      HealthCheckPath: /health

Outputs:
  ALBDNS:
    Value: !GetAtt GalleryALB.DNSName