AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Cluster, Task Definitions, Services

Resources:
  GalleryECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: GalleryCluster

  GalleryExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  GalleryFrontendService:
    Type: AWS::ECS::Service
    DependsOn: GalleryALBListener
    Properties:
      Cluster: !Ref GalleryECSCluster
      LaunchType: FARGATE
      DesiredCount: 2
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !ImportValue GalleryPrivateSubnet1
            - !ImportValue GalleryPrivateSubnet2
          AssignPublicIp: DISABLED
          SecurityGroups: [!Ref GalleryALBSecurityGroup]
      LoadBalancers:
        - ContainerName: frontend
          ContainerPort: 80
          TargetGroupArn: !Ref GalleryFrontendTargetGroup
      TaskDefinition: !Ref GalleryFrontendTask

  GalleryBackendService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref GalleryECSCluster
      LaunchType: FARGATE
      DesiredCount: 2
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !ImportValue GalleryPrivateSubnet1
            - !ImportValue GalleryPrivateSubnet2
          AssignPublicIp: DISABLED
          SecurityGroups: [!Ref GalleryALBSecurityGroup]
      LoadBalancers:
        - ContainerName: backend
          ContainerPort: 8080
          TargetGroupArn: !Ref GalleryBackendTargetGroup
      TaskDefinition: !Ref GalleryBackendTask

  GalleryFrontendTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: gallery-frontend-task
      RequiresCompatibilities: [FARGATE]
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt GalleryExecutionRole.Arn
      ContainerDefinitions:
        - Name: frontend
          Image: <replace-with-ecr-uri>
          PortMappings:
            - ContainerPort: 80

  GalleryBackendTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: gallery-backend-task
      RequiresCompatibilities: [FARGATE]
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt GalleryExecutionRole.Arn
      ContainerDefinitions:
        - Name: backend
          Image: <replace-with-ecr-uri>
          PortMappings:
            - ContainerPort: 8080