AWSTemplateFormatVersion: '2010-09-09'
Description: CodePipeline with GitHub Actions-style source and ECR push

Resources:
  GalleryArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: gallery-artifact-bucket
      Tags:
        - Key: lab
          Value: week5_project

  GalleryPipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodePipelineFullAccess
        - arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser

  GalleryPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt GalleryPipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref GalleryArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: <github-owner>
                Repo: <repo-name>
                Branch: main
                OAuthToken: <github-token>
        - Name: Build
          Actions:
            - Name: BuildDockerImages
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: gallery-codebuild-project
        - Name: Deploy
          Actions:
            - Name: DeployBlueGreen
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CodeDeployToECS
                Version: 1
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ApplicationName: gallery-codedeploy-app
                DeploymentGroupName: gallery-deployment-group
