AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Bucket for image uploads

Resources:
  GalleryImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: gallery-image-storage
      Tags:
        - Key: lab
          Value: week5_project

  GalleryBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref GalleryImageBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::124355655853:user/admin
            Action: s3:*
            Resource: !Sub "arn:aws:s3:::${GalleryImageBucket}/*"

Outputs:
  ImageBucketName:
    Value: !Ref GalleryImageBucket
    Export:
      Name: GalleryImageBucketName
