version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:eu-west-1:124355655853:task-definition/gallery-task"
        LoadBalancerInfo:
          ContainerName: "gallery-container"
          ContainerPort: 8081
