version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:iam::124355655853:role/wk5-gallery-ecs-role"
        LoadBalancerInfo:
          ContainerName: "gallery-container"
          ContainerPort: 80
