name: Upload Infra Templates and CodeDeploy Files to S3

on:
  push:
    branches:
      - main

jobs:
  upload:
    name: Upload Infrastructure Files
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET: ${{ secrets.TEMPLATE_BUCKET_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync infra templates to S3
        run: |
          aws s3 sync infra/ s3://$S3_BUCKET/ \
            --exclude "*" \
            --include "*.yaml" \
            --include "*.yml"

      - name: Zip CodeDeploy files
        run: |
          cd pipeline
          zip ../codedeploy-bundle.zip appspec.yml taskdef.json

      - name: Upload codedeploy-bundle.zip to S3
        run: |
          aws s3 cp codedeploy-bundle.zip s3://$S3_BUCKET/codedeploy-bundle.zip

      - name: Print uploaded template URLs
        run: |
          echo "Templates uploaded to:"
          find infra -name "*.yaml" -o -name "*.yml" | while read file; do
            filename=$(basename "$file")
            echo "https://$S3_BUCKET.s3.${AWS_REGION}.amazonaws.com/$filename"
          done
